package orientation_test

import (
	"bytes"
	"strings"
	"testing"

	"github.com/phosphorco/workbench-go/internal/contract"
	"github.com/phosphorco/workbench-go/internal/orientation"
)

func TestRenderIsByteConvergentFromExplicitFacts(t *testing.T) {
	instructions := fixtureInstructions()

	first, err := orientation.Render(instructions)
	if err != nil {
		t.Fatal(err)
	}
	second, err := orientation.Render(instructions)
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(first, second) {
		t.Fatalf("same explicit facts rendered different bytes:\nfirst:\n%s\nsecond:\n%s", first, second)
	}

	reordered := instructions
	reordered.Subject.Entrypoints = reversed(instructions.Subject.Entrypoints)
	reordered.Resources = reversed(instructions.Resources)
	reordered.GeneratedPaths = reversed(instructions.GeneratedPaths)
	reordered.HandOwnedPaths = reversed(instructions.HandOwnedPaths)
	canonical, err := orientation.Render(reordered)
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(first, canonical) {
		t.Fatalf("unordered participating-repository facts changed generated bytes:\nfirst:\n%s\nreordered:\n%s", first, canonical)
	}

	wantFacts := []string{
		"change desired state in the Subject or repository declarations",
		"## Participating repositories",
		"Reconcile this Workbench: `workbench setup`",
		"Record a Workbench Snapshot: `workbench snapshot`",
		"Branch: \"workbench/proof-0.2.0\"",
		"Base branch: \"main\"",
		"\"@workbench-entry\" - shape \"packageScope\"; GitHub \"phosphorco/workbench-fixture-entry\"; path \"pkg/@workbench-entry\"; branch \"workbench/proof-0.2.0\"; health \"healthy\"",
		"\"phosphorco/workbench-fixture-library\" - shape \"repository\"; GitHub \"phosphorco/workbench-fixture-library\"; path \"repos/workbench-fixture-library\"; branch \"workbench/proof-0.2.0\"; health \"wrongBranch\"",
		"`workbench setup`",
		"`workbench commit`",
		"`workbench snapshot`",
		"`workbench prune`",
		"`AGENTS.md` is generated and ignored",
		"`AGENTS.pkl` is Git-owned and is never rewritten by Workbench",
	}
	for _, fact := range wantFacts {
		if !strings.Contains(string(first), fact) {
			t.Fatalf("orientation omits %q:\n%s", fact, first)
		}
	}
	retiredVocabulary := "wo" + "rld"
	if strings.Contains(strings.ToLower(string(first)), retiredVocabulary) {
		t.Fatalf("orientation contains retired vocabulary:\n%s", first)
	}
}

func TestRenderUpdatesAndRemovesParticipatingRepositoriesTruthfully(t *testing.T) {
	instructions := fixtureInstructions()
	before, err := orientation.Render(instructions)
	if err != nil {
		t.Fatal(err)
	}

	instructions.Resources = instructions.Resources[:1]
	instructions.Resources[0].Health = "healthy"
	instructions.Resources[0].Branch = "workbench/new-line"
	instructions.Subject.WorkLine.Branch = "workbench/new-line"
	instructions.Subject.Entrypoints = []string{"https://github.com/phosphorco/workbench-fixture-library"}
	after, err := orientation.Render(instructions)
	if err != nil {
		t.Fatal(err)
	}

	if !strings.Contains(string(before), "@workbench-entry") {
		t.Fatal("precondition: entry resource absent from initial orientation")
	}
	for _, removedFact := range []string{"@workbench-entry", "phosphorco/workbench-fixture-entry", "pkg/@workbench-entry", "workbench/proof-0.2.0", "wrongBranch"} {
		if strings.Contains(string(after), removedFact) {
			t.Fatalf("stale fact %q survived repository-closure/Subject update:\n%s", removedFact, after)
		}
	}
	for _, currentFact := range []string{"phosphorco/workbench-fixture-library", "repos/workbench-fixture-library", "workbench/new-line", "healthy"} {
		if !strings.Contains(string(after), currentFact) {
			t.Fatalf("current fact %q absent after update:\n%s", currentFact, after)
		}
	}
}

func TestRenderRejectsInvalidFactsWithoutAcquiringWriteAuthority(t *testing.T) {
	instructions := fixtureInstructions()
	instructions.Resources[0].CanonicalPath = "repos/lie"
	if _, err := orientation.Render(instructions); err == nil {
		t.Fatal("shape-inconsistent orientation facts rendered")
	}

	var pureProjection func(contract.AgentInstructions) ([]byte, error) = orientation.Render
	if pureProjection == nil {
		t.Fatal("Render is unavailable")
	}
}

func fixtureInstructions() contract.AgentInstructions {
	return contract.AgentInstructions{
		Prose: "# Context-owned instructions\n\nDo the work.\n",
		Subject: contract.AgentSubject{
			WorkLine: contract.WorkLine{Branch: "workbench/proof-0.2.0", BaseBranch: "main"},
			Entrypoints: []string{
				"https://github.com/phosphorco/workbench-fixture-library",
				"https://github.com/phosphorco/workbench-fixture-entry",
			},
		},
		Resources: []contract.AgentResource{
			{
				Identity:      "phosphorco/workbench-fixture-library",
				GitHub:        "phosphorco/workbench-fixture-library",
				Shape:         contract.ResourceShape{Kind: contract.RepositoryShape},
				CanonicalPath: "repos/workbench-fixture-library",
				Branch:        "workbench/proof-0.2.0",
				Health:        "wrongBranch",
			},
			{
				Identity:      "@workbench-entry",
				GitHub:        "phosphorco/workbench-fixture-entry",
				Shape:         contract.ResourceShape{Kind: contract.PackageScopeShape, Scope: "@workbench-entry"},
				CanonicalPath: "pkg/@workbench-entry",
				Branch:        "workbench/proof-0.2.0",
				Health:        "healthy",
			},
		},
		GeneratedPaths: []string{"tsconfig.json", "AGENTS.md", "package.json"},
		HandOwnedPaths: []string{"src/", "AGENTS.pkl"},
	}
}

func reversed[T any](values []T) []T {
	result := make([]T, len(values))
	for index := range values {
		result[len(values)-1-index] = values[index]
	}
	return result
}
